# Generated by Django 2.1.7 on 2019-04-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190408_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='useractivitymap',
            name='is_delete',
        ),
    ]
