# Generated by Django 2.1.7 on 2019-04-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190408_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=None, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='head_img',
            field=models.ImageField(null=True, upload_to='images', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='self_desc',
            field=models.CharField(max_length=100, null=True, verbose_name='个人描述'),
        ),
    ]
