# Generated by Django 2.1.7 on 2019-05-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('activity_name', models.CharField(max_length=20, verbose_name='活动名称')),
                ('activity_desc', models.CharField(max_length=100, verbose_name='活动描述')),
                ('activity_time', models.DateTimeField(verbose_name='活动时间')),
                ('activity_site', models.CharField(max_length=50, verbose_name='活动地点')),
                ('limit_num', models.IntegerField(default=10, verbose_name='人数限制')),
                ('activity_type', models.CharField(max_length=20, verbose_name='活动类型')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'jw_activity',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('comment', models.CharField(max_length=150, null=True, verbose_name='评论')),
                ('img', models.ImageField(null=True, upload_to='images', verbose_name='图片')),
            ],
            options={
                'verbose_name': '动态',
                'verbose_name_plural': '动态',
                'db_table': 'jw_dynamic',
            },
        ),
        migrations.CreateModel(
            name='UserActivityMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='活动id')),
            ],
            options={
                'verbose_name': '用户活动映射',
                'verbose_name_plural': '用户活动映射',
                'db_table': 'jw_uamap',
            },
        ),
    ]
