# Generated by Django 2.1.7 on 2019-04-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='is_delete',
        ),
    ]
