# Generated by Django 2.1.7 on 2019-04-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20190415_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
